(uiop:define-package frontend.template
  (:nicknames template)
  (:use #:cl)
  (:import-from :spinneret
                #:with-html
                #:with-html-string)
  (:export #:with-page
           #:render-error-message)
  (:export #:unix-to-timestamp)
  (:export #:render-upvotes
           #:render-pagination))

(in-package #:frontend.template)

(defmacro with-page ((&key title (userp nil)) &body body)
  "Generates and returns an html document as a string.
The BODY, if supplied, must be a list of forms generated by spinneret's with-html macro."
  `(with-html-string
     (:doctype)
     (:html
      (:head
       (:link :rel "stylesheet" :href "/static/style.css")
       (:title ,title))
      (:body
       (:header
        (:nav
         (:a :href "/" "Home")
         (if ,userp
             (:a :href "/logout" "Logout")
             (:a :href "/login" "Login"))))
       (:main ,@body)
       (:footer (:p "footer"))))))

(defun render-error-message (msg)
  "Template for an error message."
  (with-html
    (:div :class "notice" (:strong "⚠️ Error:️ ") msg)))

(defconstant +unix-epoch-offset+
  (encode-universal-time 0 0 0 1 1 1970 0)
  "Used for converting unix time to universal time.")

;; TODO: make the human readable timestamp something like: n minutes/hours/days ago
(defun unix-to-timestamp (time &optional (timezone 0))
  "Decodes TIME (unix seconds) using TIMEZONE and returns two timestamps strings.
TIMEZONE defaults to 0 (UTC).

The first return value is a machine-readable timestamp.
The second value is a human-readable timestamp."
  (multiple-value-bind (second minute hour day month year)
      (decode-universal-time (+ +unix-epoch-offset+ time) timezone)
    (values
     (format nil "~4,'0d-~2,'0d-~2,'0dT~2,'0d:~2,'0d:~2,'0d"
             year month day hour minute second)
     (format nil "~2,'0d/~2,'0d/~4,'0d ~2,'0d:~2,'0d" day month year hour minute))))

(defun render-upvotes (id upvote-count)
  (with-html
   (:div
    :style "display: inline-block; padding-left: 1rem;"
    (:form
     :action (format nil "/upvote/~a" id) :method "post"
     :style "display: inline;"
     (:button :type "submit"
              :style "background: none; border: 0; color: var(--accent); padding: 0; margin: 0;
                 text-decoration: underline; cursor: pointer;" "▲"))
    (:span " ")
    (:span (format nil "~a upvotes" upvote-count)))))

(defun render-pagination (offset resource-url)
  (with-html
   (:div
    :style "padding-top: 1rem;"
    (if (or (eq 'null offset) (null offset))
        (:p :style "font-style: italic;" "You have reached the end.")
       (:form
          :action resource-url :method "get"
          :style "display: flex; align-items: baseline; gap: 0.5rem; flex-wrap: wrap;"
          (:label :for "limit" :style "display: inline;" "Items per page:")
          (:select :name "limit" :style "width: auto;"
             (:option :selected t :value 20 "20")
             (:option :value 50 "50")
             (:option :value 100 "100"))
          (:input :type "hidden" :name "offset" :value offset)
          (:button :type "submit" "Load more"))))))
