(uiop:define-package frontend.template
  (:use #:cl)
  (:import-from :spinneret
                #:with-html
                #:with-html-string)
  (:export #:with-page
           #:render-error-message))
(in-package #:frontend.template)

(defmacro with-page ((&key title (userp nil)) &body body)
  "Generates and returns an html document as a string.
The BODY, if supplied, must be a list of forms generated by spinneret's with-html macro."
  `(with-html-string
     (:doctype)
     (:html
      (:head
       (:link :rel "stylesheet" :href "/static/style.css")
       (:title ,title))
      (:body
       (:header
        (:nav
         (:a :href "/" "Home")
         (if ,userp
             (:a :href "/logout" "Logout")
             (:a :href "/login" "Login"))))
       (:main ,@body)
       (:footer (:p "footer"))))))

(defun render-error-message (msg)
  "Template for an error message."
  (with-html
    (:div :class "notice" (:strong "⚠️ Error:️ ") msg)))

